### PR TITLE
Extend with environment variables support

### PR DESCRIPTION
**Pull request by DeviaVir**
Sometimes my environment is passed only certain environment variables, which I don't actually know yet when I'm invoking the `sqs-to-lambda` command, it's therefore useful to be able to just assume those environment variables exist on the system without having to know them on the invoke command.

The semantics on aliases and perhaps renamings I'll leave to you, these seemed sane to me but I understand that is a subjective view.

### CODE REVIEW

**Comment by DeviaVir** [comment]
This is how my tests look like:

```
~ node index.js --queue-url testQueue --function-name testFunction --region testRegion                                                                                                                                                                                                   127
argv { _: [],
  'queue-url': 'testQueue',
  queueUrl: 'testQueue',
  'function-name': 'testFunction',
  functionName: 'testFunction',
  region: 'testRegion',
  '$0': 'index.js' }
region testRegion
queueUrl testQueue
functionName testFunction
```

```
~ AWS_QUEUE=testQueue2 AWS_REGION=testRegion2 AWS_FUNCTION=testFunction2 node index.js --queue-url testQueue --function-name testFunction --region testRegion
argv { _: [],
  'queue-url': 'testQueue',
  queueUrl: [ 'testQueue', 'testQueue2' ],
  'function-name': 'testFunction',
  functionName: [ 'testFunction', 'testFunction2' ],
  region: 'testRegion',
  queue: 'testQueue2',
  function: 'testFunction2',
  '$0': 'index.js' }
region testRegion
queueUrl testQueue
functionName testFunction
```

```
~ AWS_QUEUE=testQueue2 AWS_REGION=testRegion2 AWS_FUNCTION=testFunction2 node index.js
argv { _: [],
  queue: 'testQueue2',
  queueUrl: 'testQueue2',
  region: 'testRegion2',
  function: 'testFunction2',
  functionName: 'testFunction2',
  '$0': 'index.js' }
region testRegion2
queueUrl testQueue2
functionName testFunction2
```

**Comment by robinjmurphy** [comment]
Hi @DeviaVir. Sounds like a good idea to me. I'll take a look tomorrow for you and send some feedback.

**Comment by DeviaVir** [comment]
Hi @robinjmurphy, did you get a chance to look into this one already? :smile:

**Comment by robinjmurphy** [comment]
Hi @DeviaVir I've had a look and it's a nice feature of yargs. I'd like to propose that we use the environment variables:

```
AWS_REGION
AWS_FUNCTION_NAME
AWS_QUEUE_URL
```

Which means we can simplify the code needed to implement this. I've created a version using these variables in a branch. Let me know if the change looks good to you and I can merge my branch.

https://github.com/robinjmurphy/sqs-to-lambda/compare/env_var_support

**Comment by DeviaVir** [comment]
@robinjmurphy Those environment variables work for me. Note, that if you do not port https://github.com/robinjmurphy/sqs-to-lambda/pull/1/files#diff-168726dbe96b3ce427e7fedce31bb0bcR22 as well, you can end up with a situation where `argv.functionName` (or any other) is actually an array; for example when you pass both (this is the precedence bit I added).

I have combined both into this PR, what do you think?

**Comment by robinjmurphy** [comment]
Ah I didn't realise that. Yep I can merge.

**Comment by DeviaVir** [comment]
:+1: awesome!

**Comment by robinjmurphy** [comment]
Released as 1.1.0 to npm. Thanks for your help :+1:

**Pull request merged**
